server:
  port: 8088
dubbo:
  #服务器名称唯一
  application:
    name: customer
    qosEnable: false
  #注册中心配置，使用zookeeper做注册中心
  registry:
    address: zookeeper://127.0.0.1:2181
  monitor:
    address: 127.0.0.1:20889